

name: Test Automation WorkFlow

on:
schedule:
  - cron: 00 18 * * *
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
        
    - name: Running Test Automation Framework With Maven
      run: mvn test 

   - name: Upload Test logs
     if: always()
     uses: actions/upload-artifact@v4.6.2
     with:
      name: Test Logs
       path: logs/

       - name: Upload Test Reports
     if: always()
     uses: actions/upload-artifact@v4.6.2
     with:
      name: Test cucumber Reports
       path: Cucumber-reports.html

       - name: Upload Test Reports
         run: echo "Tests Completed"

   
